apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "duna.fullname" . }}
  labels:
    {{- include "duna.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "duna.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "duna.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.imageCredentials.pullSecret }}
      imagePullSecrets:
        - name: {{ .Values.imageCredentials.pullSecret }}
      {{- else if eq .Values.imageCredentials.enabled true }}
      imagePullSecrets:
        - name: {{ include "duna.fullname" . }}-pull-secret
      {{- end }}
      serviceAccountName: {{ include "duna.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: >-
            {{ .Values.image.repository }}
            {{- if .Values.image.digest }}@{{ .Values.image.digest }}
            {{- else }}:{{ .Values.image.tag | default .Chart.AppVersion }}{{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          env:       
            - name: DUNA_RUNTIME
              value: "true"

          volumeMounts:
          {{- if .Values.favicon.enabled }}
            - name: favicon-volume
              mountPath: /app/favicon.ico
              subPath: favicon.ico
          {{- end }}
          {{- if .Values.robotstxt.enabled }}
            - name: robotstxt-volume
              mountPath: /app/robots.txt
              subPath: robots.txt
              readOnly: true
          {{- end }}
            - name: {{ include "duna.fullname" . }}-config-volume
              mountPath: /app/app-config.json
              subPath: app-config.json
              readOnly: true

          # 
          # Set container configuration
          #
          ports:
            - name: http
              containerPort: 1080
              protocol: TCP
          
          livenessProbe:
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
            httpGet:
              path: {{ .Values.duna.basePath }}/health
              port: http
          
          readinessProbe:
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
            httpGet:
              path: {{ .Values.duna.basePath }}/health
              port: http

          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      {{- if .Values.favicon.enabled }}
        - name: favicon-volume
          configMap:
            name: {{ include "duna.fullname" . }}-favicon
      {{- end }}
      {{- if .Values.robotstxt.enabled }}
        - name: robotstxt-volume
          configMap:
            name: {{ include "duna.fullname" . }}-robotstxt
      {{- end }}
        - name:  {{ include "duna.fullname" . }}-config-volume
          secret:
            secretName: {{ .Values.duna.configSecret }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
