{{- if .Values.ingress.enabled -}}
{{- $fullName := include "duna.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- $host := (urlParse .Values.duna.url).host }}
{{- $faviconPath := default "/favicon.ico" .Values.favicon.path }}
{{- if semverCompare ">=1.19" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else -}}
apiVersion: networking.k8s.io/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "duna.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.ingress.config }}
  {{- toYaml . | nindent 4 }}  # This line injects the config settings
  {{- end }}
spec:
  {{- if and .Values.ingress.className (semverCompare ">=1.18" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.ingress.externalTrafficPolicy }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        - {{ $host | quote }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    - host: {{ $host | quote }}
      http:
        paths:
          - path: {{ .Values.duna.basePath }}
            {{- if (semverCompare ">=1.18" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: "Prefix"
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
              {{- else }}
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}
              {{- end }}
          - path: {{ .Values.duna.frontEndBasePath }}
            {{- if (semverCompare ">=1.18" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: "Prefix"
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
              {{- else }}
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}
              {{- end }}
          {{- if .Values.favicon.enabled }}
          - path: {{ $faviconPath }}
            {{- if (semverCompare ">=1.18" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: "Exact"
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
              {{- else }}
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}
              {{- end }}
          {{- end }}
          {{- if .Values.robotstxt.enabled }}
          - path: /robots.txt
            {{- if (semverCompare ">=1.18" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: "Exact"
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
              {{- else }}
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}
              {{- end }}
          {{- end }}
{{- end }}
