{{- if .Values.robotstxt.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "duna.fullname" . }}-robotstxt
data:
  robots.txt: |
{{- with .Values.robotstxt.content }}
{{ . | nindent 4 }}
{{- else }}
    User-agent: *
    Disallow: /
{{- end }}
{{- end }}
