{{- if .Values.imageCredentials.pullSecret }}
# If using already configured secret, we don't need our own
{{- else if eq .Values.imageCredentials.enabled true }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "duna.fullname" . }}-pull-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}
